import { Metadata } from 'next';
import { PostSearchState } from '@/components/PostSearchState';
import { PostsState } from '@/components/Post-state';

export const metadata: Metadata = {
  title: 'Blog | Next App',
  description: 'Generated by create next app',
};

export default function Blog() {
  return (
    <>
      <h1>Blog page</h1>
      <PostSearchState />
      <PostsState />
    </>
  );
}
